name: tankolog
version: 1.0.0
author: Gábor Ginter
description: A (yet private) mobile application to track expenses on my car
homepage: https://github.com/tarkinmuffin/tankolog
dependencies:
  bootjack: any
  firebase: any
  polymer: any
transformers:
- polymer:
    entry_points: web/tankolog.html
